import { ExternalLink, FileText, LockKeyhole, ShieldCheck } from 'lucide-react';
import { Card, DemoBadge, SectionTitle, SourceLine, TrustNotice } from '../components/UI';

const sources = [
  ['국립수산과학원 패류독소 속보', 'https://www.nifs.go.kr/board/actionBoard0021List.do?selectPage=5', '해역별 패류독소 발생·변동 및 채취금지 확인'],
  ['부산광역시 해양수산 안전검사', 'https://www.busan.go.kr/depart/safetyinspection', '부산시 수산물 안전검사 안내'],
  ['해양수산부 해양환경 공동활용체계', 'https://www.vadahub.go.kr/analyze/gallery/model/index.do', '해양 수질·환경 측정자료 활용 경로'],
  ['식품안전나라', 'https://www.foodsafetykorea.go.kr/main.do', '회수·판매중지 및 식품 보관·위생 정보'],
];

export default function AboutPage() { return <div className="container page-stack about-page"><div className="page-intro"><div><p className="eyebrow">ABOUT SEASAFE BUSAN</p><h1>안심海 <em>SeaSafe Busan</em></h1><p>부산 시민과 관광객을 위한 개인 맞춤형 해산물 섭취 의사결정 지원 웹앱입니다.</p></div><DemoBadge /></div><TrustNotice /><div className="about-grid"><Card><div className="about-icon"><ShieldCheck /></div><h2>문제에서 출발했습니다</h2><p>패류독소·수산물 검사·해양환경·식품 보관 정보가 여러 기관에 나뉘어 있어, 시민이 ‘지금 먹어도 되는지’를 한 화면에서 판단하기 어렵습니다.</p><p>안심海는 지역 정보, 개인 조건, 보관 이력을 분리해 보여주고, 숫자 하나로 위험을 숨기지 않는 것을 목표로 합니다.</p></Card><Card><div className="about-icon coral"><LockKeyhole /></div><h2>개인정보를 보내지 않습니다</h2><p>건강 조건과 사진은 서버나 별도 백엔드로 전송하지 않고 브라우저 메모리에서만 처리합니다. 저장이 필요한 설정은 최소화했습니다.</p><p>사진 분석은 실제 부패·병원균 판정이 아닌 시각적 교육 시뮬레이션입니다.</p></Card></div><Card><SectionTitle eyebrow="OFFICIAL SOURCES" title="데이터 출처" /><div className="source-list">{sources.map(([name, url, description]) => <a key={name} href={url} target="_blank" rel="noreferrer" className="source-card"><FileText size={20} /><span><strong>{name}</strong><small>{description}</small></span><ExternalLink size={15} /></a>)}</div><div className="source-note"><DemoBadge /><span>지역 수치·위험 변화 그래프는 발표용 시연 데이터입니다. 실제 공공데이터 API 또는 정기 수집으로 교체할 때는 관측 시각·갱신 실패·원문 링크를 함께 관리해야 합니다.</span></div></Card><Card><SectionTitle eyebrow="PROJECT NOTES" title="무료 기술과 한계" /><div className="tech-pills"><span>React</span><span>Vite</span><span>TypeScript</span><span>Leaflet</span><span>OpenStreetMap</span><span>LocalStorage 미사용</span></div><ul className="limit-list"><li>실시간 API·로그인·백엔드가 없는 정적 프로토타입입니다.</li><li>샘플 데이터는 안전을 보장하지 않으며, 반드시 공식 원문과 기준일을 확인해야 합니다.</li><li>의료 진단·법적 판단·식품 안전 보증을 대신하지 않습니다.</li></ul><SourceLine name="안심海 프로토타입 기준일" url="https://www.foodsafetykorea.go.kr/main.do" date="2026-08-06" /></Card></div>; }
