import { useMemo, useState } from 'react';
import { Check, ClipboardCheck, Copy, RotateCcw, Share2 } from 'lucide-react';
import regions from '../data/regions.json';
import { Card, DemoBadge, RiskBars, RiskBadge, SourceLine } from '../components/UI';
import { evaluateDecision } from '../logic/decisionEngine';
import type { DecisionInput, DecisionResult, PersonalCondition, Region, Seafood, StorageMode } from '../types';

const typedRegions = regions as Region[];
const seafoodOptions: Seafood[] = ['굴', '홍합', '새우', '고등어', '광어', '오징어'];
const conditions: PersonalCondition[] = ['알레르기', '임신', '고령자', '면역저하', '간질환', '주의조건 없음'];

export default function DecisionPage() {
  const [input, setInput] = useState<DecisionInput>({ seafood: '굴', regionId: 'gijang', raw: true, storageMode: '냉장', storageHours: 6, temperature: 4, conditions: [] });
  const [result, setResult] = useState<DecisionResult | null>(null);
  const update = <K extends keyof DecisionInput>(key: K, value: DecisionInput[K]) => setInput((prev) => ({ ...prev, [key]: value }));
  const toggleCondition = (condition: PersonalCondition) => setInput((prev) => ({ ...prev, conditions: condition === '주의조건 없음' ? ['주의조건 없음'] : prev.conditions.includes(condition) ? prev.conditions.filter((item) => item !== condition) : [...prev.conditions.filter((item) => item !== '주의조건 없음'), condition] }));
  const region = useMemo(() => typedRegions.find((item) => item.id === input.regionId) ?? typedRegions[0], [input.regionId]);
  return <div className="container page-stack decision-page"><div className="page-intro"><div><p className="eyebrow">PERSONAL CHECK</p><h1>오늘 이 해산물,<br /><em>먹어도 될까?</em></h1><p>최대 1분이면 됩니다. 입력한 정보는 서버로 전송하지 않고 이 브라우저에서만 판정합니다.</p></div><div className="decision-badge"><ClipboardCheck size={26} /><span>규칙 기반<br />판정 엔진</span></div></div><Card className="decision-form-card"><div className="step-title"><span className="step-number">01</span><div><h2>간단한 5가지 확인</h2><p>정답을 맞히는 테스트가 아니라 현재 정보 기준 행동을 고르는 과정입니다.</p></div></div><Field label="해산물 종류" hint="지원 6종"><div className="chip-grid">{seafoodOptions.map((item) => <button key={item} className={`choice-chip ${input.seafood === item ? 'active' : ''}`} onClick={() => update('seafood', item)}>{item}</button>)}</div></Field><Field label="구입 또는 채취 지역"><select value={input.regionId} onChange={(event) => update('regionId', event.target.value)}>{typedRegions.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.riskLevel === 'unknown' ? '최신 데이터 없음' : item.riskLevel === 'danger' ? '채취·섭취 주의' : item.riskLevel === 'caution' ? '주의 필요' : '현재 확인된 특별한 주의정보 없음'}</option>)}</select></Field><Field label="섭취 방법"><div className="segmented"><button className={!input.raw ? 'active' : ''} onClick={() => update('raw', false)}>가열</button><button className={input.raw ? 'active' : ''} onClick={() => update('raw', true)}>생식</button></div></Field><Field label="보관 상태" hint="판정에도 함께 반영"><div className="storage-mini-grid"><label>방식<select value={input.storageMode} onChange={(event) => update('storageMode', event.target.value as StorageMode)}><option>실온</option><option>냉장</option><option>냉동</option></select></label><label>시간<select value={input.storageHours} onChange={(event) => update('storageHours', Number(event.target.value))}>{[1, 3, 6, 12, 24, 48].map((hours) => <option key={hours} value={hours}>{hours}시간</option>)}</select></label><label>온도<input type="number" value={input.temperature} onChange={(event) => update('temperature', Number(event.target.value))} aria-label="보관 온도" /><small>℃</small></label></div></Field><Field label="개인 주의조건" hint="복수 선택 가능"><div className="condition-grid">{conditions.map((condition) => <button key={condition} className={`condition-chip ${input.conditions.includes(condition) ? 'active' : ''}`} onClick={() => toggleCondition(condition)}>{input.conditions.includes(condition) && <Check size={15} />}{condition}</button>)}</div></Field><div className="form-preview"><span>선택 지역</span><strong>{region.name}</strong><RiskBadge level={region.riskLevel} compact /><DemoBadge /></div><button className="primary-button full" onClick={() => setResult(evaluateDecision(input, typedRegions))}>지금 판정하기 <ClipboardCheck size={18} /></button></Card>{result && <DecisionResultCard result={result} input={input} region={region} onReset={() => setResult(null)} />}</div>;
}

function Field({ label, hint, children }: { label: string; hint?: string; children: React.ReactNode }) { return <div className="form-field"><div className="field-label"><label>{label}</label>{hint && <span>{hint}</span>}</div>{children}</div>; }

function DecisionResultCard({ result, input, region, onReset }: { result: DecisionResult; input: DecisionInput; region: Region; onReset: () => void }) {
  const [shared, setShared] = useState(false);
  const canShare = typeof navigator !== 'undefined' && 'share' in navigator && typeof (navigator as Navigator & { share?: unknown }).share === 'function';
  const shareText = `안심海 판정: ${result.headline}\n해산물 ${input.seafood} · 지역 ${region.name}\n${result.actions[0]}\n${location.href}`;
  const share = async () => { if (canShare) await navigator.share({ title: '안심海 맞춤 판정', text: shareText }); else { await navigator.clipboard?.writeText(shareText); setShared(true); window.setTimeout(() => setShared(false), 1800); } };
  return <Card className={`decision-result result-${result.level === '가능' ? 'safe' : result.level === '섭취 피하기' ? 'danger' : result.level === '정보 부족' ? 'unknown' : 'caution'}`}><div className="result-topline"><span className="result-kicker">안심海의 현재 정보 기준</span><DemoBadge /></div><div className="result-headline"><span className="result-icon">{result.level === '가능' ? '✓' : result.level === '섭취 피하기' ? '!' : result.level === '정보 부족' ? '?' : '△'}</span><div><p>최종 행동 판정</p><h2>{result.headline}</h2></div></div><RiskBars region={result.regionRisk} personal={result.personalRisk} storage={result.storageRisk} /><div className="reason-columns"><div><h3>판정 이유</h3><ul>{result.reasons.map((reason) => <li key={reason}>{reason}</li>)}</ul></div><div><h3>권장 행동</h3><ul>{result.actions.map((action) => <li key={action}>{action}</li>)}</ul></div></div><SourceLine name={result.sourceName} url={result.sourceUrl} date={result.referenceDate} /><div className="result-actions"><button className="secondary-button" onClick={share}>{shared ? <Check size={16} /> : canShare ? <Share2 size={16} /> : <Copy size={16} />}{shared ? '복사됨' : canShare ? '결과 공유' : '결과 복사'}</button><button className="ghost-button" onClick={onReset}><RotateCcw size={16} /> 다시 입력</button></div><p className="medical-note">의료 진단이 아닌 안전정보 지원 서비스입니다. 증상이나 알레르기 반응이 있으면 의료기관의 안내를 받으세요.</p></Card>;
}
