import { ArrowRight, CheckCircle2, Fish, MapPinned, Snowflake, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';
import regions from '../data/regions.json';
import { Card, DemoBadge, RiskBadge, SectionTitle, SourceLine, TrustNotice } from '../components/UI';
import type { Region } from '../types';

const typedRegions = regions as Region[];

export default function HomePage() {
  const cautionCount = typedRegions.filter((region) => region.riskLevel === 'caution' || region.riskLevel === 'danger').length;
  return <div className="container home-page"><section className="hero"><div className="hero-copy"><div className="hero-kicker"><span className="wave-dot" />부산 해산물 안전정보 한눈에</div><h1>오늘 이 해산물,<br /><em>먹어도 될까?</em></h1><p>지역 위험, 개인 주의조건, 보관 상태를 한 번에 살펴보고 지금 할 수 있는 행동을 제안받으세요.</p><Link to="/decision" className="primary-button large">맞춤 판정 시작하기 <ArrowRight size={18} /></Link><div className="hero-meta"><span><CheckCircle2 size={15} /> 브라우저에서만 처리</span><span><CheckCircle2 size={15} /> 시연용 데이터 분리</span></div></div><div className="hero-visual" aria-hidden="true"><div className="ocean-orb"><span className="fish-emoji">🐟</span><span className="bubble b1" /><span className="bubble b2" /><span className="bubble b3" /></div><div className="hero-note"><span>오늘의 기준일</span><strong>2026.08.06</strong><small>최신 공식 원문 확인 권장</small></div></div></section><TrustNotice /><section className="home-section"><SectionTitle eyebrow="BUSAN COAST WATCH" title="부산 연안 주의정보" ><Link className="text-link" to="/map">전체 지도 보기 <ArrowRight size={15} /></Link></SectionTitle><div className="summary-grid"><Card className="summary-highlight"><div className="summary-icon"><MapPinned size={22} /></div><strong>{typedRegions.length}개 지역</strong><span>기장부터 다대포까지</span><b className="warning-text">{cautionCount}곳 주의 플래그</b><Link to="/map" className="inline-link">지역별 원문 확인 <ArrowRight size={14} /></Link></Card>{typedRegions.slice(0, 3).map((region) => <div className="region-row" key={region.id}><div className={`region-pin pin-${region.riskLevel}`} /><div><strong>{region.name}</strong><span>{region.summary.replace('시연용 ', '').slice(0, 39)}{region.summary.length > 39 ? '…' : ''}</span></div><RiskBadge level={region.riskLevel} compact /></div>)}</div></section><section className="home-section"><SectionTitle eyebrow="MAKE A SAFER CHOICE" title="안심海가 도와드리는 것" /><div className="feature-grid"><FeatureCard icon={<MapPinned />} title="부산 위험지도" text="해역별 주의 단계와 패류독소·검사 정보를 원문 링크와 함께 확인해요." to="/map" accent="teal" /><FeatureCard icon={<Fish />} title="먹어도 될까?" text="해산물·지역·생식 여부·개인 조건을 조합해 행동 중심으로 안내해요." to="/decision" accent="coral" featured /><FeatureCard icon={<Snowflake />} title="보관 시뮬레이터" text="사진은 내 기기에서만 처리하고, 시간·온도별 외관 변화를 교육용으로 보여줘요." to="/storage" accent="blue" /></div></section><section className="quiz-callout"><div><div className="eyebrow">5-MINUTE LEARNING</div><h2>해산물 안전, 퀴즈로<br />가볍게 확인해볼까요?</h2><p>공식 자료를 바탕으로 만든 O/X 5문제. 틀린 문제는 관련 기능으로 다시 연결됩니다.</p></div><div className="quiz-art"><Sparkles size={30} /><span>O / X</span></div><Link to="/quiz" className="secondary-button">퀴즈 풀기 <ArrowRight size={16} /></Link></section><section className="data-footnote"><DemoBadge /><p>현재 화면의 지역 위험 수치와 변화 그래프는 교체 가능한 시연용 데이터입니다. 실제 서비스에서는 국립수산과학원·부산시·식품안전나라의 최신 원문을 확인해 갱신해야 합니다.</p><SourceLine name="국립수산과학원 패류독소 속보" url="https://www.nifs.go.kr/board/actionBoard0021List.do?selectPage=5" date="2026-08-06" /></section></div>;
}

function FeatureCard({ icon, title, text, to, accent, featured = false }: { icon: React.ReactNode; title: string; text: string; to: string; accent: string; featured?: boolean }) {
  return <Link to={to} className={`feature-card accent-${accent} ${featured ? 'featured' : ''}`}><div className="feature-icon">{icon}</div><h3>{title}</h3><p>{text}</p><span className="feature-more">자세히 보기 <ArrowRight size={14} /></span></Link>;
}
